docs(practices): data-fetching docs
atls/convention pull request #14
Opened 2021-08-29 15:31 UTC by TFK70

2021-08-29 16:48 UTC, TorinAsakura requested changes

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +- [Graphql](https://ru.reactjs.org/docs/hooks-intro.html)
!

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +**Graphql** - это протокол, использующийся для общения между клиентом и сервером в более удобном формате
не является протоколом, протокол всё тот же - HTTP, учи мат. часть

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +У нас есть фрагмент - список тудушек. Тудушки необходимо получать из внешнего источника данных, соответственно:
это скорее пре-реквизиты/условия, в блоке задачи - пиши только то, что относится непосредственно к задаче

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +1. Сделать запрос
какой/куда?

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +2. Дождаться данных
каких? сколько ждать? условия?

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +3. Отрисовать
где/как/чем?

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Url источника данных указывается в `ApolloProvider`. При использовании Nextjs это достаточно сделать один раз в `_app.tsx` (с этим поможет библиотека [next-app-with-apollo](https://github.com/atls/ne
обычно в (…) указывают вещи, которые незначительны и, "как-бы-между-прочим", а у тебя это основа контекста

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Давайте сделаем рабочий прототип:
У нас не урок: "а давайте без "давайте""?)

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +  const { data, loading, error } = useQuery(GET_TASKS) // исполняем запрос
укажи в дисклеймере, что комментарии на русском обусловлены лишь тем, что это учебно-показательный материал и русские комментарии строго запрещены в рабочем коде

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +      {data && data.tasks.map((task) => <h1>{task}</h1>)}
для наглядности и приближенности к боевым действиям - я бы рисовал компонент @ui/heading или типа того, а то выглядит как-то уж совсем оторванно

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Разберем как это работает:
когда разбираешь после кода - происходит расфокусировка, это лучше делать по ходу написания

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +### Почему для исполнения запроса используется хук?
дать ссыль на то, что такое хук или в дисклеймер

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +### Теперь оформим это получше
ненужно создавать прецедент для мыслительных связей, пиши как есть: приводим к боевому виду или типа того

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Выполнять все эти операции в одном фрагменте - плохая практика, смотреть на компонент разросшийся до размеров Эйфелевой башни всегда неприятно. Давайте декомпозировать:
без давайте, будь краток, много текста в данном случае - вообще не айс

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +0. Так как работа с данными - это в своем роде инкапсулированный процесс, то создадим директорию `data`, в которой будем описывать всю логику
ай-ай, не пародируй, если бы ты придерживался этого стиля с самого начала ещё ок, а так - брысь

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Все просто
большинство это деморализует и нервирует, типа: "бля! тут написано, что "всё просто"! Ебать я тупой! Пойду убьюсь банкой майонеза(((("

2021-08-29 16:48 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Но на деле это довольно просто обходится с помощью коллбека. Создадим файл `useData.ts`:
опять

2021-08-29 17:22 UTC, TFK70 commented on practices/data-fetching/README.md
> +0. Так как работа с данными - это в своем роде инкапсулированный процесс, то создадим директорию `data`, в которой будем описывать всю логику
аа у меня это обоснованно:

до начала рефакторинга есть [список](https://github.com/atls/convention/blame/docs/data-fetching/practices/data-fetching/README.md#L87) с шагами, которые нам нужно декомпозировать, а шаги в рефакторинге соответствуют шагам из списка

2021-08-30 12:13 UTC, TorinAsakura requested changes

2021-08-30 12:13 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Это обходится с помощью коллбека. Создадим файл `useData.ts`:
рекомендую указывать путь, так как создание файла вне контекста часто сбивает с толку, вариант в духе
Создадим файл: /workspace/project-one/fragments/list-block/useData.ts - выглядит куда более явным

2021-08-30 12:13 UTC, TorinAsakura commented on practices/data-fetching/README.md
> +Выполнять все эти операции в одном фрагменте - плохая практика негативно влияющая на чистоту и компактность кода. Следовательно код нужно декомпозировать:
Этот блок вообще мусорный и его можно выбросить. Можно оставить в качестве "ВНИМАНИЕ! ГАВНОКОД - ПЛОХО!", но, не более

2021-08-30 14:55 UTC, TorinAsakura approved these changes

2021-08-30 14:55 UTC, merged